import { defineConfig } from 'oxlint'

export const oxlintVueFallbackRules = [
  'typescript/consistent-type-imports',
  'unocss/order',
  'unocss/order-attributify',
  'unused-imports/no-unused-imports',
  'unused-imports/no-unused-vars',
] as const

export const oxlintJsPluginRules = {
  'antfu/no-top-level-await': 'error',
  'command/command': 'error',
  'e18e/ban-dependencies': 'error',
  'e18e/prefer-array-at': 'error',
  'e18e/prefer-array-fill': 'error',
  'e18e/prefer-array-from-map': 'error',
  'e18e/prefer-array-some': 'error',
  'e18e/prefer-array-to-reversed': 'error',
  'e18e/prefer-array-to-sorted': 'error',
  'e18e/prefer-array-to-spliced': 'error',
  'e18e/prefer-date-now': 'error',
  'e18e/prefer-includes': 'error',
  'e18e/prefer-nullish-coalescing': 'error',
  'e18e/prefer-object-has-own': 'error',
  'e18e/prefer-regex-test': 'error',
  'e18e/prefer-spread-syntax': 'error',
  'e18e/prefer-static-regex': 'error',
  'e18e/prefer-string-fromcharcode': 'error',
  'e18e/prefer-timer-args': 'error',
  'e18e/prefer-url-canparse': 'error',
  'eslint-comments/no-aggregating-enable': 'error',
  'eslint-comments/no-duplicate-disable': 'error',
  'eslint-comments/no-unlimited-disable': 'error',
  'eslint-comments/no-unused-enable': 'error',
  'nuxt/prefer-import-meta': 'error',
  'perfectionist/sort-exports': ['error', { order: 'asc', type: 'natural' }],
  'perfectionist/sort-named-exports': ['error', { order: 'asc', type: 'natural' }],
  'regexp/confusing-quantifier': 'warn',
  'regexp/control-character-escape': 'error',
  'regexp/match-any': 'error',
  'regexp/negation': 'error',
  'regexp/no-contradiction-with-assertion': 'error',
  'regexp/no-dupe-characters-character-class': 'error',
  'regexp/no-dupe-disjunctions': 'error',
  'regexp/no-empty-alternative': 'warn',
  'regexp/no-empty-capturing-group': 'error',
  'regexp/no-empty-character-class': 'error',
  'regexp/no-empty-group': 'error',
  'regexp/no-empty-lookarounds-assertion': 'error',
  'regexp/no-empty-string-literal': 'error',
  'regexp/no-escape-backspace': 'error',
  'regexp/no-extra-lookaround-assertions': 'error',
  'regexp/no-invalid-regexp': 'error',
  'regexp/no-invisible-character': 'error',
  'regexp/no-lazy-ends': 'warn',
  'regexp/no-legacy-features': 'error',
  'regexp/no-misleading-capturing-group': 'error',
  'regexp/no-misleading-unicode-character': 'error',
  'regexp/no-missing-g-flag': 'error',
  'regexp/no-non-standard-flag': 'error',
  'regexp/no-obscure-range': 'error',
  'regexp/no-optional-assertion': 'error',
  'regexp/no-potentially-useless-backreference': 'warn',
  'regexp/no-super-linear-backtracking': 'error',
  'regexp/no-trivially-nested-assertion': 'error',
  'regexp/no-trivially-nested-quantifier': 'error',
  'regexp/no-unused-capturing-group': 'error',
  'regexp/no-useless-assertions': 'error',
  'regexp/no-useless-backreference': 'error',
  'regexp/no-useless-character-class': 'error',
  'regexp/no-useless-dollar-replacements': 'error',
  'regexp/no-useless-escape': 'error',
  'regexp/no-useless-flag': 'warn',
  'regexp/no-useless-lazy': 'error',
  'regexp/no-useless-non-capturing-group': 'error',
  'regexp/no-useless-quantifier': 'error',
  'regexp/no-useless-range': 'error',
  'regexp/no-useless-set-operand': 'error',
  'regexp/no-useless-string-literal': 'error',
  'regexp/no-useless-two-nums-quantifier': 'error',
  'regexp/no-zero-quantifier': 'error',
  'regexp/optimal-lookaround-quantifier': 'warn',
  'regexp/optimal-quantifier-concatenation': 'error',
  'regexp/prefer-character-class': 'error',
  'regexp/prefer-d': 'error',
  'regexp/prefer-plus-quantifier': 'error',
  'regexp/prefer-predefined-assertion': 'error',
  'regexp/prefer-question-quantifier': 'error',
  'regexp/prefer-range': 'error',
  'regexp/prefer-set-operation': 'error',
  'regexp/prefer-star-quantifier': 'error',
  'regexp/prefer-unicode-codepoint-escapes': 'error',
  'regexp/prefer-w': 'error',
  'regexp/simplify-set-operations': 'error',
  'regexp/sort-flags': 'error',
  'regexp/strict': 'error',
  'regexp/use-ignore-case': 'error',
  'unocss/order': ['warn', { unoFunctions: ['clsx', 'classnames'], unoVariables: ['^cls', 'classNames?$'] }],
  'unocss/order-attributify': 'warn',
  'unused-imports/no-unused-imports': 'error',
  'unused-imports/no-unused-vars': [
    'error',
    {
      args: 'after-used',
      argsIgnorePattern: '^_',
      ignoreRestSiblings: true,
      vars: 'all',
      varsIgnorePattern: '^_',
    },
  ],
} as const

export default defineConfig({
  categories: {
    correctness: 'error',
    suspicious: 'error',
  },
  env: {
    browser: true,
    es2022: true,
    node: true,
  },
  ignorePatterns: ['oxfmt.config.ts', 'oxlint.config.ts'],
  jsPlugins: [
    '@e18e/eslint-plugin',
    { name: 'eslint-comments', specifier: '@eslint-community/eslint-plugin-eslint-comments' },
    { name: 'nuxt', specifier: '@nuxt/eslint-plugin' },
    { name: 'unocss', specifier: '@unocss/eslint-plugin' },
    'eslint-plugin-antfu',
    'eslint-plugin-command',
    'eslint-plugin-perfectionist',
    'eslint-plugin-regexp',
    'eslint-plugin-unused-imports',
  ],
  overrides: [
    {
      files: ['app/constants/icon.ts'],
      rules: {
        'perfectionist/sort-variable-declarations': ['warn', { type: 'natural' }],
      },
    },
    {
      files: ['**/*.config.{js,mjs,cjs,ts,mts,cts}'],
      rules: {
        'antfu/no-top-level-await': 'off',
      },
    },
    {
      files: ['**/*.d.ts'],
      rules: {
        'unicorn/require-module-specifiers': 'off',
      },
    },
    {
      files: ['app/sw.ts'],
      rules: {
        'no-restricted-globals': ['error', { message: 'Use `globalThis` instead.', name: 'global' }],
      },
    },
    {
      files: ['**/*.{test,spec}.{js,mjs,cjs,jsx,ts,mts,cts,tsx}'],
      rules: {
        'antfu/no-top-level-await': 'off',
        'e18e/ban-dependencies': 'off',
        'e18e/prefer-array-at': 'off',
        'e18e/prefer-array-from-map': 'off',
        'e18e/prefer-array-to-reversed': 'off',
        'e18e/prefer-array-to-sorted': 'off',
        'e18e/prefer-array-to-spliced': 'off',
        'e18e/prefer-spread-syntax': 'off',
        'e18e/prefer-static-regex': 'off',
        'e18e/prefer-string-fromcharcode': 'off',
        'vitest/consistent-test-it': ['error', { fn: 'it', withinDescribe: 'it' }],
        'vitest/no-focused-tests': 'error',
        'vitest/no-identical-title': 'error',
        'vitest/no-import-node-test': 'error',
        'vitest/prefer-hooks-in-order': 'error',
        'vitest/prefer-lowercase-title': [
          'error',
          {
            allowedPrefixes: [],
            ignore: [],
            ignoreTopLevelDescribe: false,
            lowercaseFirstCharacterOnly: true,
          },
        ],
      },
    },
    {
      files: ['**/*.vue'],
      rules: Object.fromEntries(oxlintVueFallbackRules.map(rule => [rule, 'off'])),
    },
  ],
  plugins: ['typescript', 'unicorn', 'oxc', 'import', 'jsdoc', 'node', 'vitest', 'vue'],
  rules: {
    'accessor-pairs': [
      'error',
      {
        enforceForClassMembers: true,
        enforceForTSTypes: false,
        getWithoutSet: false,
        setWithoutGet: true,
      },
    ],
    'array-callback-return': ['error', { allowImplicit: false, allowVoid: false, checkForEach: false }],
    eqeqeq: ['error', 'smart'],
    'eslint/sort-keys': 'warn',
    'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
    'import/first': 'error',
    'import/no-duplicates': 'off',
    'import/no-mutable-exports': 'error',
    'import/no-named-default': 'error',
    'new-cap': ['error', { capIsNew: false, newIsCap: true, properties: true }],
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-console': ['error', { allow: ['warn', 'error'] }],
    'no-empty': ['error', { allowEmptyCatch: true }],
    'no-empty-pattern': ['error', { allowObjectPatternsAsParameters: false }],
    'no-proto': 'error',
    'no-redeclare': ['error', { builtinGlobals: false }],
    'no-regex-spaces': 'error',
    'no-restricted-globals': [
      'error',
      { message: 'Use `globalThis` instead.', name: 'global' },
      { message: 'Use `globalThis` instead.', name: 'self' },
    ],
    'no-restricted-properties': [
      'error',
      { message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.', property: '__proto__' },
      { message: 'Use `Object.defineProperty` instead.', property: '__defineGetter__' },
      { message: 'Use `Object.defineProperty` instead.', property: '__defineSetter__' },
      { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupGetter__' },
      { message: 'Use `Object.getOwnPropertyDescriptor` instead.', property: '__lookupSetter__' },
    ],
    'no-sequences': ['error', { allowInParentheses: true }],
    'no-shadow': 'off',
    'no-underscore-dangle': 'off',
    'no-unreachable-loop': ['error', { ignore: [] }],
    'no-unused-expressions': [
      'error',
      {
        allowShortCircuit: true,
        allowTaggedTemplates: true,
        allowTernary: true,
      },
    ],
    'no-unused-vars': 'off',
    'no-useless-call': 'warn',
    'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-use-before-define': ['error', { classes: false, functions: false, variables: true }],
    'no-var': 'error',
    'object-shorthand': ['error', 'always', { avoidQuotes: true, ignoreConstructors: false }],
    'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
    'prefer-exponentiation-operator': 'error',
    'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'preserve-caught-error': 'off',
    'jsdoc/check-access': 'warn',
    'jsdoc/check-property-names': 'off',
    'jsdoc/check-tag-names': 'off',
    'jsdoc/empty-tags': 'warn',
    'jsdoc/implements-on-classes': 'off',
    'jsdoc/no-defaults': 'off',
    'jsdoc/require-param-name': 'warn',
    'jsdoc/require-property': 'off',
    'jsdoc/require-property-description': 'off',
    'jsdoc/require-property-name': 'off',
    'jsdoc/require-property-type': 'off',
    'jsdoc/require-returns-description': 'warn',
    'jsdoc/require-yields': 'off',
    'node/handle-callback-err': ['error', '^(err|error)$'],
    'node/no-exports-assign': 'error',
    'node/no-new-require': 'error',
    'node/no-path-concat': 'error',
    ...oxlintJsPluginRules,
    'typescript/ban-ts-comment': ['error', { 'ts-expect-error': 'allow-with-description' }],
    'typescript/consistent-type-definitions': ['error', 'interface'],
    'typescript/consistent-type-imports': [
      'error',
      {
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
        prefer: 'type-imports',
      },
    ],
    'typescript/method-signature-style': ['error', 'property'],
    'typescript/no-empty-object-type': ['error', { allowInterfaces: 'always' }],
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/prefer-literal-enum-member': 'error',
    'unicode-bom': ['error', 'never'],
    'unicorn/consistent-function-scoping': 'off',
    'unicorn/require-post-message-target-origin': 'off',
    'vitest/expect-expect': 'off',
    'vitest/hoisted-apis-on-top': 'off',
    'vitest/no-commented-out-tests': 'off',
    'vitest/no-conditional-expect': 'off',
    'vitest/no-conditional-tests': 'off',
    'vitest/no-disabled-tests': 'off',
    'vitest/no-focused-tests': 'off',
    'vitest/no-standalone-expect': 'off',
    'vitest/prefer-snapshot-hint': 'off',
    'vitest/require-awaited-expect-poll': 'off',
    'vitest/require-local-test-context-for-concurrent-snapshots': 'off',
    'vitest/require-mock-type-parameters': 'off',
    'vitest/require-to-throw-message': 'off',
    'vitest/valid-describe-callback': 'off',
    'vitest/valid-expect': 'off',
    'vitest/valid-expect-in-promise': 'off',
    'vitest/valid-title': 'off',
    'vitest/warn-todo': 'off',
    'vars-on-top': 'error',
    yoda: ['error', 'never'],
  },
})
